;;; titlecase-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from titlecase.el

(autoload 'titlecase-region "titlecase" "\
Title-case the region of English text from BEGIN to END.
Uses the style provided in `titlecase-style', unless optional
STYLE is provided.

When called interactively , or when INTERACTIVEP is non-nil,
\\[universal-argument] \\[titlecase-region] will prompt the user
for the style to use.

(fn BEGIN END &optional STYLE INTERACTIVEP)" t)
(autoload 'titlecase-line "titlecase" "\
Title-case the line at POINT.
Uses the style provided in `titlecase-style', unless optional
STYLE is provided.

When called interactively , or when INTERACTIVEP is non-nil,
POINT is the current point, and calling with
\\[universal-argument] \\[titlecase-line] will prompt the user
for the style to use.

(fn &optional POINT STYLE INTERACTIVEP)" t)
(autoload 'titlecase-sentence "titlecase" "\
Title-case the sentence at POINT.
Uses the style provided in `titlecase-style', unless optional
STYLE is provided.

When called interactively , or when INTERACTIVEP is non-nil,
POINT is the current point, and calling with
\\[universal-argument] \\[titlecase-sentence] will prompt the
user for the style to use.

(fn &optional POINT STYLE INTERACTIVEP)" t)
(autoload 'titlecase-dwim "titlecase" "\
Title-case either the region, if active, or the current line.
Uses the style provided in `titlecase-style', unless optional
STYLE is provided.

When called interactively with \\[universal-argument]
\\[titlecase-dwim], or when INTERACTIVEP is non-nil, prompt the
user for the style to use.

(fn &optional STYLE INTERACTIVEP)" t)
(register-definition-prefixes "titlecase" '("titlecase-"))


;;; Generated autoloads from titlecase-data.el

(register-definition-prefixes "titlecase-data" '("titlecase-"))

;;; End of scraped data

(provide 'titlecase-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; titlecase-autoloads.el ends here
