[window]
padding = { x = 15, y = 15 }
opacity = 0.9

[font]
normal = { family = "GoMono Nerd Font Mono" }
size = 16

[cursor]
style = { shape= "Beam", blinking = "On"}
vi_mode_style = { shape = "Block", blinking = "Off"}
 
